# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replica.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreplica.proto\x12\x07replica\",\n\x0bNodeAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x15\n\x06NodeID\x12\x0b\n\x03val\x18\x01 \x01(\t\"\x1e\n\x0bPingMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"2\n\tViewState\x12\x12\n\nprimary_id\x18\x01 \x01(\t\x12\x11\n\tbackup_id\x18\x02 \x01(\t2\xc2\x01\n\x0bReplication\x12\x37\n\x0cRegisterNode\x12\x14.replica.NodeAddress\x1a\x0f.replica.NodeID\"\x00\x12\x39\n\x0eGetNodeAddress\x12\x0f.replica.NodeID\x1a\x14.replica.NodeAddress\"\x00\x12?\n\x0fHeartbeatStream\x12\x14.replica.PingMessage\x1a\x12.replica.ViewState\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODEADDRESS._serialized_start=26
  _NODEADDRESS._serialized_end=70
  _NODEID._serialized_start=72
  _NODEID._serialized_end=93
  _PINGMESSAGE._serialized_start=95
  _PINGMESSAGE._serialized_end=125
  _VIEWSTATE._serialized_start=127
  _VIEWSTATE._serialized_end=177
  _REPLICATION._serialized_start=180
  _REPLICATION._serialized_end=374
# @@protoc_insertion_point(module_scope)
